"""Deepgram Voice Agent integration.

Deepgram owns the ears, the mouth and the turn-taking. It does not own the
reasoning: `think.endpoint` points back at this service, so every turn arrives
here as an OpenAI-shaped chat completion, runs through the LangGraph agent with
all its tools and state, and returns as text for Deepgram to speak.

That indirection is the whole point. The branching, the probe budget, the
evidence recording and the resumable state all stay in our process. Swapping
Deepgram for another speech vendor would not touch a line of agent code.
"""

from __future__ import annotations

import json
import time
import uuid
from typing import Any

from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from . import store
from .auth import candidate_session_id
from .config import get_settings

router = APIRouter(tags=["voice"])


def build_agent_settings(public_api_url: str, invite_token: str) -> dict[str, Any]:
    """The Settings frame sent to Deepgram when the socket opens.

    `greeting` is left empty on purpose -- the opening line is generated by the
    agent from the rubric and the candidate's resume, not hardcoded here.
    """
    return {
        "type": "Settings",
        "audio": {
            "input": {"encoding": "linear16", "sample_rate": 48000},
            "output": {"encoding": "linear16", "sample_rate": 24000, "container": "none"},
        },
        "agent": {
            "listen": {
                "provider": {"type": "deepgram", "version": "v2", "model": "flux-general-en"}
            },
            "speak": {"provider": {"type": "deepgram", "version": "v2", "model": "flux-kit-en"}},
            "think": {
                # No `model` key: with a custom endpoint the model is whatever the
                # endpoint decides, which for us is the provider in LLM_PROVIDER.
                "provider": {"type": "open_ai"},
                "endpoint": {
                    "url": f"{public_api_url}/v1/chat/completions/{invite_token}",
                    "headers": {"content-type": "application/json"},
                },
            },
        },
    }


class ChatMessage(BaseModel):
    role: str
    content: str | None = None


class ChatCompletionRequest(BaseModel):
    messages: list[ChatMessage] = []
    stream: bool = False


def _completion_body(text: str) -> dict[str, Any]:
    return {
        "id": f"chatcmpl-{uuid.uuid4().hex[:12]}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": get_settings().llm_model,
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": text},
                "finish_reason": "stop",
            }
        ],
    }


def _sse_chunks(text: str):
    """Deepgram speaks as soon as text arrives, so send the line then close.

    # ponytail: one chunk, not token-by-token. A turn is two or three sentences,
    # and the agent cannot emit them until its tool calls finish anyway, so
    # streaming inside a turn would buy nothing. Revisit if turns get longer.
    """
    created = int(time.time())
    chunk_id = f"chatcmpl-{uuid.uuid4().hex[:12]}"
    base = {
        "id": chunk_id,
        "object": "chat.completion.chunk",
        "created": created,
        "model": get_settings().llm_model,
    }
    first = {**base, "choices": [{"index": 0, "delta": {"role": "assistant", "content": text}}]}
    last = {**base, "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]}
    yield f"data: {json.dumps(first)}\n\n"
    yield f"data: {json.dumps(last)}\n\n"
    yield "data: [DONE]\n\n"


@router.post("/v1/chat/completions/{invite_token}")
def chat_completions(invite_token: str, body: ChatCompletionRequest):
    """OpenAI-compatible surface, one interview behind it.

    The token in the path is the session. Deepgram sends the whole conversation
    every turn; we ignore all of it except the newest candidate message, because
    the authoritative history lives in the LangGraph checkpoint, not in whatever
    the speech layer happens to be holding.
    """
    session = store.get(candidate_session_id(invite_token))
    if session is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "That interview link is no longer valid")

    latest = next(
        (m.content for m in reversed(body.messages) if m.role == "user" and m.content), ""
    )

    if not session.started:
        session.started = True
        reply = session.agent.open()
    else:
        session.record("candidate", latest)
        reply = session.agent.turn(latest)

    session.record("agent", reply, session.ctx.tool_log[-1] if session.ctx.tool_log else [])

    if body.stream:
        return StreamingResponse(_sse_chunks(reply), media_type="text/event-stream")
    return _completion_body(reply)


@router.get("/interview/{invite_token}/voice-settings")
def voice_settings(invite_token: str) -> dict[str, Any]:
    """Handed to the browser so it can open its own socket to Deepgram.

    The Deepgram key is never sent to the browser -- the client connects through
    this service's relay, which holds the key.
    """
    session = store.get(candidate_session_id(invite_token))
    if session is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "That interview link is no longer valid")
    if not session.consented:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Consent is needed before starting")

    settings = get_settings()
    if not settings.deepgram_api_key:
        raise HTTPException(
            status.HTTP_503_SERVICE_UNAVAILABLE,
            "Voice is not configured on this deployment. The typed interview still works.",
        )
    return build_agent_settings(settings.public_api_url, invite_token)
